// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/users.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	// unique account id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// alphanumeric username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// an email address
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// unix timestamp
	Created int64 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	// unix timestamp
	Updated int64 `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	// if the account is verified
	Verified bool `protobuf:"varint,6,opt,name=verified,proto3" json:"verified,omitempty"`
	// date of verification
	VerificationDate int64 `protobuf:"varint,7,opt,name=verification_date,json=verificationDate,proto3" json:"verification_date,omitempty"`
	// Store any custom data you want about your users in this fields.
	Profile              map[string]string `protobuf:"bytes,8,rep,name=profile,proto3" json:"profile,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Account) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *Account) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *Account) GetVerificationDate() int64 {
	if m != nil {
		return m.VerificationDate
	}
	return 0
}

func (m *Account) GetProfile() map[string]string {
	if m != nil {
		return m.Profile
	}
	return nil
}

type Session struct {
	// the session id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the associated user id
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	// unix timestamp
	Created int64 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	// unix timestamp
	Expires              int64    `protobuf:"varint,5,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{1}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Session) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Session) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

// Create a new user account. The email address and username for the account must be unique.
type CreateRequest struct {
	// optional account id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// the email address
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// the user password
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// optional user profile as map<string,string>
	Profile              map[string]string `protobuf:"bytes,5,rep,name=profile,proto3" json:"profile,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{2}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateRequest) GetProfile() map[string]string {
	if m != nil {
		return m.Profile
	}
	return nil
}

type CreateResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// Delete an account by id
type DeleteRequest struct {
	// the account id
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{5}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

// Read an account by id, username or email. Only one need to be specified.
type ReadRequest struct {
	// the account id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the account username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// the account email
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{6}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReadRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReadResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{7}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// Update the account username or email
type UpdateRequest struct {
	// the account id
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the new username
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// the new email address
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// the user profile as map<string,string>
	Profile              map[string]string `protobuf:"bytes,4,rep,name=profile,proto3" json:"profile,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateRequest) GetProfile() map[string]string {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

// Update the account password
type UpdatePasswordRequest struct {
	// the account id
	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// the old password
	OldPassword string `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	// the new password
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	// confirm new password
	ConfirmPassword      string   `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{10}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdatePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type UpdatePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordResponse) Reset()         { *m = UpdatePasswordResponse{} }
func (m *UpdatePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordResponse) ProtoMessage()    {}
func (*UpdatePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{11}
}

func (m *UpdatePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordResponse.Unmarshal(m, b)
}
func (m *UpdatePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordResponse.Merge(m, src)
}
func (m *UpdatePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordResponse.Size(m)
}
func (m *UpdatePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordResponse proto.InternalMessageInfo

// Read a session by the session id. In the event it has expired or is not found and error is returned.
type ReadSessionRequest struct {
	// The unique session id
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSessionRequest) Reset()         { *m = ReadSessionRequest{} }
func (m *ReadSessionRequest) String() string { return proto.CompactTextString(m) }
func (*ReadSessionRequest) ProtoMessage()    {}
func (*ReadSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{12}
}

func (m *ReadSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSessionRequest.Unmarshal(m, b)
}
func (m *ReadSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSessionRequest.Marshal(b, m, deterministic)
}
func (m *ReadSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSessionRequest.Merge(m, src)
}
func (m *ReadSessionRequest) XXX_Size() int {
	return xxx_messageInfo_ReadSessionRequest.Size(m)
}
func (m *ReadSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSessionRequest proto.InternalMessageInfo

func (m *ReadSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type ReadSessionResponse struct {
	// the session for the user
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSessionResponse) Reset()         { *m = ReadSessionResponse{} }
func (m *ReadSessionResponse) String() string { return proto.CompactTextString(m) }
func (*ReadSessionResponse) ProtoMessage()    {}
func (*ReadSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{13}
}

func (m *ReadSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSessionResponse.Unmarshal(m, b)
}
func (m *ReadSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSessionResponse.Marshal(b, m, deterministic)
}
func (m *ReadSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSessionResponse.Merge(m, src)
}
func (m *ReadSessionResponse) XXX_Size() int {
	return xxx_messageInfo_ReadSessionResponse.Size(m)
}
func (m *ReadSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSessionResponse proto.InternalMessageInfo

func (m *ReadSessionResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

// Login using username or email. The response will return a new session for successful login,
// 401 in the case of login failure and 500 for any other error
type LoginRequest struct {
	// The username of the user
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// The email address of the user
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// The password of the user
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{14}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	// The session of the logged in  user
	Session              *Session `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{15}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

// Logout a user account
type LogoutRequest struct {
	// the session id for the user to logout
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{16}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type LogoutResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{17}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

// Logout of all user's sessions
type LogoutAllRequest struct {
	// the user to logout
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAllRequest) Reset()         { *m = LogoutAllRequest{} }
func (m *LogoutAllRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutAllRequest) ProtoMessage()    {}
func (*LogoutAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{18}
}

func (m *LogoutAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAllRequest.Unmarshal(m, b)
}
func (m *LogoutAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAllRequest.Marshal(b, m, deterministic)
}
func (m *LogoutAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAllRequest.Merge(m, src)
}
func (m *LogoutAllRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutAllRequest.Size(m)
}
func (m *LogoutAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAllRequest proto.InternalMessageInfo

func (m *LogoutAllRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type LogoutAllResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutAllResponse) Reset()         { *m = LogoutAllResponse{} }
func (m *LogoutAllResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutAllResponse) ProtoMessage()    {}
func (*LogoutAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{19}
}

func (m *LogoutAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutAllResponse.Unmarshal(m, b)
}
func (m *LogoutAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutAllResponse.Marshal(b, m, deterministic)
}
func (m *LogoutAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutAllResponse.Merge(m, src)
}
func (m *LogoutAllResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutAllResponse.Size(m)
}
func (m *LogoutAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutAllResponse proto.InternalMessageInfo

// Verify the email address of an account from a token sent in an email to the user.
type VerifyEmailRequest struct {
	// The token from the verification email
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailRequest) Reset()         { *m = VerifyEmailRequest{} }
func (m *VerifyEmailRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailRequest) ProtoMessage()    {}
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{20}
}

func (m *VerifyEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailRequest.Unmarshal(m, b)
}
func (m *VerifyEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailRequest.Marshal(b, m, deterministic)
}
func (m *VerifyEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailRequest.Merge(m, src)
}
func (m *VerifyEmailRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailRequest.Size(m)
}
func (m *VerifyEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailRequest proto.InternalMessageInfo

func (m *VerifyEmailRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyEmailResponse) Reset()         { *m = VerifyEmailResponse{} }
func (m *VerifyEmailResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyEmailResponse) ProtoMessage()    {}
func (*VerifyEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{21}
}

func (m *VerifyEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyEmailResponse.Unmarshal(m, b)
}
func (m *VerifyEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyEmailResponse.Marshal(b, m, deterministic)
}
func (m *VerifyEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyEmailResponse.Merge(m, src)
}
func (m *VerifyEmailResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyEmailResponse.Size(m)
}
func (m *VerifyEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyEmailResponse proto.InternalMessageInfo

// Send a verification email to a user.
type SendVerificationEmailRequest struct {
	// email address to send the verification code
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// subject of the email
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Text content of the email. Include '$micro_verification_link' which will be replaced by a verification link
	TextContent string `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// The url to redirect to after successful verification
	RedirectUrl string `protobuf:"bytes,4,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	// The url to redirect to incase of failure
	FailureRedirectUrl string `protobuf:"bytes,5,opt,name=failure_redirect_url,json=failureRedirectUrl,proto3" json:"failure_redirect_url,omitempty"`
	// Display name of the sender for the email. Note: the email address will still be 'noreply@email.m3ocontent.com'
	FromName             string   `protobuf:"bytes,6,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationEmailRequest) Reset()         { *m = SendVerificationEmailRequest{} }
func (m *SendVerificationEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendVerificationEmailRequest) ProtoMessage()    {}
func (*SendVerificationEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{22}
}

func (m *SendVerificationEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationEmailRequest.Unmarshal(m, b)
}
func (m *SendVerificationEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendVerificationEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationEmailRequest.Merge(m, src)
}
func (m *SendVerificationEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendVerificationEmailRequest.Size(m)
}
func (m *SendVerificationEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationEmailRequest proto.InternalMessageInfo

func (m *SendVerificationEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendVerificationEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendVerificationEmailRequest) GetTextContent() string {
	if m != nil {
		return m.TextContent
	}
	return ""
}

func (m *SendVerificationEmailRequest) GetRedirectUrl() string {
	if m != nil {
		return m.RedirectUrl
	}
	return ""
}

func (m *SendVerificationEmailRequest) GetFailureRedirectUrl() string {
	if m != nil {
		return m.FailureRedirectUrl
	}
	return ""
}

func (m *SendVerificationEmailRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

type SendVerificationEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendVerificationEmailResponse) Reset()         { *m = SendVerificationEmailResponse{} }
func (m *SendVerificationEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendVerificationEmailResponse) ProtoMessage()    {}
func (*SendVerificationEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{23}
}

func (m *SendVerificationEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendVerificationEmailResponse.Unmarshal(m, b)
}
func (m *SendVerificationEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendVerificationEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendVerificationEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendVerificationEmailResponse.Merge(m, src)
}
func (m *SendVerificationEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendVerificationEmailResponse.Size(m)
}
func (m *SendVerificationEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendVerificationEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendVerificationEmailResponse proto.InternalMessageInfo

// Send an email with a verification code to reset password.
// Call "ResetPassword" endpoint once user provides the code.
type SendPasswordResetEmailRequest struct {
	// email address to send reset for
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// subject of the email
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Text content of the email. Don't forget to include the string '$code' which will be replaced by the real verification link
	// HTML emails are not available currently.
	TextContent string `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// Display name of the sender for the email. Note: the email address will still be 'noreply@email.m3ocontent.com'
	FromName string `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	// Number of secs that the password reset email is valid for, defaults to 1800 secs (30 mins)
	Expiration           int64    `protobuf:"varint,5,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordResetEmailRequest) Reset()         { *m = SendPasswordResetEmailRequest{} }
func (m *SendPasswordResetEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendPasswordResetEmailRequest) ProtoMessage()    {}
func (*SendPasswordResetEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{24}
}

func (m *SendPasswordResetEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Unmarshal(m, b)
}
func (m *SendPasswordResetEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendPasswordResetEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordResetEmailRequest.Merge(m, src)
}
func (m *SendPasswordResetEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendPasswordResetEmailRequest.Size(m)
}
func (m *SendPasswordResetEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordResetEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordResetEmailRequest proto.InternalMessageInfo

func (m *SendPasswordResetEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendPasswordResetEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendPasswordResetEmailRequest) GetTextContent() string {
	if m != nil {
		return m.TextContent
	}
	return ""
}

func (m *SendPasswordResetEmailRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *SendPasswordResetEmailRequest) GetExpiration() int64 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

type SendPasswordResetEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendPasswordResetEmailResponse) Reset()         { *m = SendPasswordResetEmailResponse{} }
func (m *SendPasswordResetEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendPasswordResetEmailResponse) ProtoMessage()    {}
func (*SendPasswordResetEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{25}
}

func (m *SendPasswordResetEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendPasswordResetEmailResponse.Unmarshal(m, b)
}
func (m *SendPasswordResetEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendPasswordResetEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendPasswordResetEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendPasswordResetEmailResponse.Merge(m, src)
}
func (m *SendPasswordResetEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendPasswordResetEmailResponse.Size(m)
}
func (m *SendPasswordResetEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendPasswordResetEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendPasswordResetEmailResponse proto.InternalMessageInfo

// Reset password with the code sent by the "SendPasswordResetEmail" endpoint.
type ResetPasswordRequest struct {
	// the email to reset the password for
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// The code from the verification email
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// the new password
	NewPassword string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	// confirm new password
	ConfirmPassword      string   `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{26}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResetPasswordRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *ResetPasswordRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

type ResetPasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{27}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

// List all users. Returns a paged list of results
type ListRequest struct {
	Offset uint32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	// Maximum number of records to return. Default limit is 25.
	// Maximum limit is 1000. Anything higher will return an error.
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{28}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListResponse struct {
	Users                []*Account `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{29}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetUsers() []*Account {
	if m != nil {
		return m.Users
	}
	return nil
}

// Login using email only - Passwordless
type SendMagicLinkRequest struct {
	// the email address of the user
	Email   string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// Text content of the email. Don't forget to include the string '$micro_verification_link' which will be replaced by the real verification link
	// HTML emails are not available currently.
	TextContent string `protobuf:"bytes,3,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// Display name of the sender for the email. Note: the email address will still be 'support@m3o.com'
	FromName string `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	// Your web site address, example www.example.com or user.example.com
	Address string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// Endpoint name where your http request handler handles MagicLink by
	// calling M3O VerifyToken endpoint. You can return as a result a success,
	// failed or redirect to another page.
	Endpoint             string   `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMagicLinkRequest) Reset()         { *m = SendMagicLinkRequest{} }
func (m *SendMagicLinkRequest) String() string { return proto.CompactTextString(m) }
func (*SendMagicLinkRequest) ProtoMessage()    {}
func (*SendMagicLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{30}
}

func (m *SendMagicLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMagicLinkRequest.Unmarshal(m, b)
}
func (m *SendMagicLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMagicLinkRequest.Marshal(b, m, deterministic)
}
func (m *SendMagicLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMagicLinkRequest.Merge(m, src)
}
func (m *SendMagicLinkRequest) XXX_Size() int {
	return xxx_messageInfo_SendMagicLinkRequest.Size(m)
}
func (m *SendMagicLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMagicLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMagicLinkRequest proto.InternalMessageInfo

func (m *SendMagicLinkRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SendMagicLinkRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendMagicLinkRequest) GetTextContent() string {
	if m != nil {
		return m.TextContent
	}
	return ""
}

func (m *SendMagicLinkRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *SendMagicLinkRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendMagicLinkRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

type SendMagicLinkResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMagicLinkResponse) Reset()         { *m = SendMagicLinkResponse{} }
func (m *SendMagicLinkResponse) String() string { return proto.CompactTextString(m) }
func (*SendMagicLinkResponse) ProtoMessage()    {}
func (*SendMagicLinkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{31}
}

func (m *SendMagicLinkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMagicLinkResponse.Unmarshal(m, b)
}
func (m *SendMagicLinkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMagicLinkResponse.Marshal(b, m, deterministic)
}
func (m *SendMagicLinkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMagicLinkResponse.Merge(m, src)
}
func (m *SendMagicLinkResponse) XXX_Size() int {
	return xxx_messageInfo_SendMagicLinkResponse.Size(m)
}
func (m *SendMagicLinkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMagicLinkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMagicLinkResponse proto.InternalMessageInfo

// Check whether the token attached to MagicLink is valid or not.
// Ideally, you need to call this endpoint from your http request
// handler that handles the endpoint which is specified in the
// SendMagicLink request.
type VerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{32}
}

func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	IsValid              bool     `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1c161a4c7514913, []int{33}
}

func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

func (m *VerifyTokenResponse) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *VerifyTokenResponse) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *VerifyTokenResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "user.Account")
	proto.RegisterMapType((map[string]string)(nil), "user.Account.ProfileEntry")
	proto.RegisterType((*Session)(nil), "user.Session")
	proto.RegisterType((*CreateRequest)(nil), "user.CreateRequest")
	proto.RegisterMapType((map[string]string)(nil), "user.CreateRequest.ProfileEntry")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "user.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "user.DeleteResponse")
	proto.RegisterType((*ReadRequest)(nil), "user.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "user.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterMapType((map[string]string)(nil), "user.UpdateRequest.ProfileEntry")
	proto.RegisterType((*UpdateResponse)(nil), "user.UpdateResponse")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "user.UpdatePasswordRequest")
	proto.RegisterType((*UpdatePasswordResponse)(nil), "user.UpdatePasswordResponse")
	proto.RegisterType((*ReadSessionRequest)(nil), "user.ReadSessionRequest")
	proto.RegisterType((*ReadSessionResponse)(nil), "user.ReadSessionResponse")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "user.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "user.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "user.LogoutResponse")
	proto.RegisterType((*LogoutAllRequest)(nil), "user.LogoutAllRequest")
	proto.RegisterType((*LogoutAllResponse)(nil), "user.LogoutAllResponse")
	proto.RegisterType((*VerifyEmailRequest)(nil), "user.VerifyEmailRequest")
	proto.RegisterType((*VerifyEmailResponse)(nil), "user.VerifyEmailResponse")
	proto.RegisterType((*SendVerificationEmailRequest)(nil), "user.SendVerificationEmailRequest")
	proto.RegisterType((*SendVerificationEmailResponse)(nil), "user.SendVerificationEmailResponse")
	proto.RegisterType((*SendPasswordResetEmailRequest)(nil), "user.SendPasswordResetEmailRequest")
	proto.RegisterType((*SendPasswordResetEmailResponse)(nil), "user.SendPasswordResetEmailResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "user.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "user.ResetPasswordResponse")
	proto.RegisterType((*ListRequest)(nil), "user.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "user.ListResponse")
	proto.RegisterType((*SendMagicLinkRequest)(nil), "user.SendMagicLinkRequest")
	proto.RegisterType((*SendMagicLinkResponse)(nil), "user.SendMagicLinkResponse")
	proto.RegisterType((*VerifyTokenRequest)(nil), "user.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "user.VerifyTokenResponse")
}

func init() {
	proto.RegisterFile("proto/users.proto", fileDescriptor_b1c161a4c7514913)
}

var fileDescriptor_b1c161a4c7514913 = []byte{
	// 1198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x6b, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0x65, 0xbd, 0x3c, 0x7a, 0x54, 0x5e, 0xcb, 0x36, 0x43, 0xe7, 0xa1, 0x32, 0x05, 0xea,
	0x36, 0x80, 0x5c, 0xd8, 0x0d, 0x9a, 0x3a, 0x40, 0x80, 0x34, 0xce, 0x8f, 0x14, 0x4e, 0x1b, 0x30,
	0xb5, 0x7f, 0x14, 0x05, 0x04, 0x5a, 0x5c, 0x19, 0xac, 0x29, 0x52, 0xe5, 0x52, 0x76, 0x7c, 0x89,
	0x9e, 0xa1, 0x37, 0xe8, 0xff, 0x22, 0x17, 0xe8, 0x39, 0x8a, 0xde, 0xa3, 0xd8, 0xc7, 0x50, 0xbb,
	0xb4, 0x64, 0x34, 0x80, 0x8d, 0xfc, 0xe3, 0x3c, 0x76, 0x66, 0x76, 0x1e, 0xdf, 0x2c, 0x61, 0x75,
	0x92, 0x26, 0x59, 0xb2, 0x33, 0x65, 0x34, 0x65, 0x7d, 0xf1, 0x4d, 0xca, 0x9c, 0x70, 0xff, 0x2a,
	0x41, 0xed, 0xf9, 0x70, 0x98, 0x4c, 0xe3, 0x8c, 0xb4, 0xa1, 0x14, 0x06, 0xb6, 0xd5, 0xb3, 0xb6,
	0x57, 0xbc, 0x52, 0x18, 0x10, 0x07, 0xea, 0x5c, 0x27, 0xf6, 0xc7, 0xd4, 0x2e, 0x09, 0x6e, 0x4e,
	0x93, 0x2e, 0x54, 0xe8, 0xd8, 0x0f, 0x23, 0x7b, 0x59, 0x08, 0x24, 0x41, 0x6c, 0xa8, 0x0d, 0x53,
	0xea, 0x67, 0x34, 0xb0, 0xcb, 0x3d, 0x6b, 0x7b, 0xd9, 0x43, 0x92, 0x4b, 0xa6, 0x93, 0x40, 0x48,
	0x2a, 0x52, 0xa2, 0x48, 0xee, 0xe5, 0x9c, 0xa6, 0xe1, 0x28, 0xa4, 0x81, 0x5d, 0xed, 0x59, 0xdb,
	0x75, 0x2f, 0xa7, 0xc9, 0x23, 0x58, 0x95, 0xdf, 0x43, 0x3f, 0x0b, 0x93, 0x78, 0xc0, 0x4f, 0xd8,
	0x35, 0x71, 0xbe, 0xa3, 0x0b, 0x0e, 0xfc, 0x8c, 0x92, 0xaf, 0xa1, 0x36, 0x49, 0x93, 0x51, 0x18,
	0x51, 0xbb, 0xde, 0x5b, 0xde, 0x6e, 0xec, 0x3a, 0x7d, 0x1e, 0x6e, 0x5f, 0x5d, 0xaf, 0xff, 0x46,
	0x0a, 0x5f, 0xc6, 0x59, 0x7a, 0xe9, 0xa1, 0xaa, 0xb3, 0x0f, 0x4d, 0x5d, 0x40, 0x3a, 0xb0, 0x7c,
	0x46, 0x2f, 0x55, 0x16, 0xf8, 0x27, 0xbf, 0xea, 0xb9, 0x1f, 0x4d, 0x31, 0x07, 0x92, 0xd8, 0x2f,
	0x3d, 0xb1, 0x5c, 0x0a, 0xb5, 0xb7, 0x94, 0xb1, 0x30, 0x89, 0xaf, 0xe4, 0x6e, 0x03, 0xaa, 0xdc,
	0xf9, 0xab, 0x40, 0x9d, 0x52, 0xd4, 0xf5, 0x19, 0xa2, 0xef, 0x26, 0x61, 0x4a, 0x19, 0x66, 0x48,
	0x91, 0xee, 0xbf, 0x16, 0xb4, 0x5e, 0x08, 0x2d, 0x8f, 0xfe, 0x36, 0xa5, 0xec, 0x26, 0x2a, 0xe5,
	0x40, 0x7d, 0xe2, 0x33, 0x76, 0x91, 0xa4, 0x32, 0x90, 0x15, 0x2f, 0xa7, 0xc9, 0xfe, 0x2c, 0x91,
	0x15, 0x91, 0xc8, 0x9e, 0x4c, 0xa4, 0x11, 0xc3, 0x2d, 0xa4, 0xf3, 0x5b, 0x68, 0xa3, 0x0b, 0x36,
	0x49, 0x62, 0x46, 0xc9, 0xe7, 0x50, 0xf3, 0x65, 0xf5, 0x84, 0x85, 0xc6, 0x6e, 0xcb, 0x28, 0xa9,
	0x87, 0x52, 0xf7, 0x01, 0xb4, 0x0e, 0x68, 0x44, 0x17, 0x66, 0xc8, 0xed, 0x40, 0x1b, 0x15, 0xa4,
	0x6d, 0xf7, 0x47, 0x68, 0x78, 0xd4, 0x0f, 0x6e, 0x2c, 0xa5, 0xee, 0x37, 0xd0, 0x94, 0x06, 0x3f,
	0x34, 0xf8, 0xbf, 0x2d, 0x68, 0x1d, 0x89, 0x69, 0xb8, 0xb9, 0xfa, 0x6a, 0x35, 0x2c, 0xeb, 0x35,
	0x34, 0xfc, 0xdc, 0x42, 0x0d, 0x3b, 0xd0, 0x46, 0x17, 0x2a, 0xcf, 0x7f, 0x58, 0xb0, 0x2e, 0x59,
	0x6f, 0x54, 0x83, 0xe1, 0x2d, 0x67, 0x33, 0x62, 0x19, 0x33, 0xf2, 0x29, 0x34, 0x93, 0x28, 0x18,
	0xe4, 0xfd, 0x29, 0x9d, 0x34, 0x92, 0x28, 0x40, 0x0b, 0x5c, 0x25, 0xa6, 0x17, 0x33, 0x15, 0x79,
	0xf7, 0x46, 0x4c, 0x2f, 0x72, 0x95, 0x2f, 0xa0, 0x33, 0x4c, 0xe2, 0x51, 0x98, 0x8e, 0x07, 0x85,
	0x4e, 0xff, 0x44, 0xf1, 0x51, 0xd5, 0xb5, 0x61, 0xa3, 0x18, 0xa1, 0x0a, 0x7e, 0x0f, 0x08, 0xaf,
	0xa9, 0x9a, 0x72, 0x0c, 0xfc, 0x1e, 0x00, 0x93, 0x9c, 0x41, 0x5e, 0xa6, 0x15, 0xc5, 0x79, 0x15,
	0xb8, 0xcf, 0x60, 0xcd, 0x38, 0x34, 0xeb, 0x07, 0xa5, 0x63, 0xf6, 0x03, 0xea, 0xa1, 0xd4, 0xfd,
	0x05, 0x9a, 0x87, 0xc9, 0x69, 0x98, 0xbb, 0xd3, 0xab, 0x6f, 0x2d, 0xaa, 0x7e, 0x69, 0xd1, 0x74,
	0x2f, 0x9b, 0xd3, 0xed, 0x3e, 0x81, 0x96, 0xb2, 0xfe, 0xa1, 0x71, 0xf5, 0xc5, 0xc9, 0x64, 0x9a,
	0xfd, 0xcf, 0x3c, 0x74, 0xa0, 0x8d, 0xfa, 0x2a, 0x9d, 0x8f, 0xa0, 0x23, 0x39, 0xcf, 0xa3, 0x08,
	0x8d, 0x6c, 0x42, 0x8d, 0xbb, 0x9b, 0x59, 0x50, 0x6d, 0xe0, 0xae, 0xc1, 0xaa, 0xa6, 0xac, 0x2c,
	0x7c, 0x09, 0xe4, 0x98, 0x03, 0xff, 0xe5, 0x4b, 0x7e, 0x51, 0xb4, 0xd1, 0x85, 0x4a, 0x96, 0x9c,
	0xd1, 0x58, 0x59, 0x90, 0x84, 0xbb, 0x0e, 0x6b, 0x86, 0xae, 0x32, 0xf1, 0x8f, 0x05, 0x77, 0xdf,
	0xd2, 0x38, 0x38, 0xd6, 0x16, 0x48, 0xd1, 0x9a, 0xcc, 0xa9, 0x55, 0xd8, 0x6d, 0x6c, 0x7a, 0xf2,
	0x2b, 0x1d, 0x66, 0x2a, 0xd7, 0x48, 0xf2, 0x66, 0xcc, 0xe8, 0xbb, 0x6c, 0x30, 0x4c, 0xe2, 0x8c,
	0xc6, 0x19, 0x36, 0x23, 0xe7, 0xbd, 0x90, 0x2c, 0xae, 0x92, 0xd2, 0x20, 0x4c, 0xe9, 0x30, 0x1b,
	0x4c, 0xd3, 0x48, 0x35, 0x62, 0x03, 0x79, 0x47, 0x69, 0x44, 0xbe, 0x82, 0xee, 0xc8, 0x0f, 0xa3,
	0x69, 0x4a, 0x07, 0x86, 0x6a, 0x45, 0xa8, 0x12, 0x25, 0xf3, 0xb4, 0x13, 0x5b, 0xb0, 0x32, 0x4a,
	0x93, 0xf1, 0x40, 0x34, 0x46, 0x55, 0x96, 0x99, 0x33, 0x7e, 0xf0, 0xc7, 0xd4, 0x7d, 0x00, 0xf7,
	0x16, 0x5c, 0x52, 0xa5, 0xe1, 0x4f, 0x4b, 0x6a, 0x68, 0x3d, 0x4f, 0xb3, 0xdb, 0xce, 0x83, 0x11,
	0x72, 0xd9, 0x0c, 0x99, 0xdc, 0x07, 0x10, 0x2b, 0x4f, 0x04, 0xab, 0x96, 0xa0, 0xc6, 0x71, 0x7b,
	0x70, 0x7f, 0x51, 0xc0, 0xea, 0x4e, 0xbf, 0x5b, 0xd0, 0x15, 0xec, 0x22, 0xd4, 0xcc, 0xbf, 0x0a,
	0x81, 0xf2, 0x30, 0x09, 0x10, 0xc5, 0xc4, 0xf7, 0x0d, 0x23, 0xcb, 0x26, 0xac, 0x17, 0xe2, 0x51,
	0x91, 0x3e, 0x85, 0xc6, 0x61, 0xc8, 0x32, 0x0d, 0x0a, 0x93, 0xd1, 0x88, 0x51, 0xb9, 0x2a, 0x5a,
	0x9e, 0xa2, 0x78, 0xdc, 0x51, 0x38, 0x0e, 0x65, 0xaa, 0x5b, 0x9e, 0x24, 0xdc, 0x3d, 0x68, 0xca,
	0xc3, 0x6a, 0x82, 0x1f, 0x42, 0x45, 0xbc, 0xec, 0x6c, 0x4b, 0x40, 0x7d, 0x61, 0xcf, 0x48, 0x99,
	0xfb, 0xde, 0x82, 0x2e, 0x4f, 0xdf, 0x6b, 0xff, 0x34, 0x1c, 0x1e, 0x86, 0xf1, 0xd9, 0xc7, 0x2a,
	0xb3, 0x0d, 0x35, 0x3f, 0x08, 0x52, 0xca, 0x98, 0xea, 0x6d, 0x24, 0x39, 0x6c, 0xd1, 0x38, 0x98,
	0x24, 0x61, 0x9c, 0x61, 0x3f, 0x23, 0xcd, 0x33, 0x59, 0x88, 0xbe, 0x88, 0x08, 0x3f, 0xf1, 0xa1,
	0xbf, 0x1e, 0x11, 0x18, 0x22, 0x82, 0xd2, 0x55, 0xf9, 0xbb, 0x03, 0xf5, 0x90, 0x0d, 0xce, 0xfd,
	0x48, 0x61, 0x50, 0xdd, 0xab, 0x85, 0xec, 0x98, 0x93, 0x3a, 0x38, 0x96, 0xae, 0x03, 0x47, 0x7e,
	0xab, 0x31, 0x65, 0xcc, 0x3f, 0xa5, 0x2a, 0x21, 0x48, 0xee, 0xbe, 0xaf, 0x43, 0xf9, 0x88, 0xd1,
	0x94, 0x3c, 0x86, 0xaa, 0x7c, 0xdf, 0x90, 0xb5, 0x39, 0x0f, 0x2a, 0xa7, 0x6b, 0x32, 0xd5, 0xf5,
	0x96, 0xc8, 0x0e, 0x94, 0xf9, 0x3a, 0x21, 0xab, 0x52, 0xae, 0x3d, 0x5a, 0x1c, 0xa2, 0xb3, 0xf2,
	0x03, 0x8f, 0xa1, 0x2a, 0xd7, 0x19, 0xfa, 0x31, 0x96, 0x3e, 0xfa, 0x29, 0xac, 0x69, 0x71, 0x4c,
	0x3e, 0x91, 0xf0, 0x98, 0xf1, 0xa2, 0xc2, 0x63, 0x85, 0x57, 0xd4, 0x12, 0x79, 0x8d, 0x1b, 0x3f,
	0x9f, 0x8f, 0x2d, 0xdd, 0x41, 0x61, 0x12, 0x9d, 0xbb, 0xf3, 0x85, 0xb9, 0xb9, 0x5d, 0xa8, 0x88,
	0xf5, 0x44, 0xd4, 0xdd, 0xf4, 0x4d, 0xe8, 0xac, 0x19, 0x3c, 0x3d, 0x72, 0xb9, 0x29, 0xc8, 0x4c,
	0x61, 0xb6, 0xa6, 0x30, 0xf2, 0xc2, 0x2e, 0x5a, 0x22, 0xcf, 0x60, 0x25, 0x5f, 0x30, 0x64, 0x43,
	0x57, 0x9a, 0xad, 0x27, 0x67, 0xf3, 0x0a, 0x3f, 0x3f, 0x7f, 0x20, 0x5f, 0x90, 0xf8, 0x0b, 0x60,
	0xcf, 0x8a, 0x61, 0xbe, 0x17, 0x9c, 0x3b, 0x73, 0x24, 0xba, 0x15, 0x6d, 0x4b, 0xa1, 0x95, 0xab,
	0x4b, 0x0e, 0xad, 0xcc, 0x5b, 0x69, 0x4b, 0xe4, 0x44, 0x8e, 0xc7, 0x15, 0xb8, 0x27, 0x2e, 0xf6,
	0xeb, 0xe2, 0x85, 0xe7, 0x3c, 0xbc, 0x56, 0x27, 0xf7, 0x41, 0x61, 0x63, 0x3e, 0xfe, 0x12, 0xcd,
	0xc0, 0xc2, 0x75, 0xe2, 0x7c, 0x76, 0xbd, 0x52, 0xee, 0xe6, 0x7b, 0x68, 0x19, 0x98, 0x49, 0x1c,
	0x4c, 0xdf, 0x55, 0x60, 0x77, 0xb6, 0xe6, 0xca, 0xf4, 0xd9, 0xe1, 0x48, 0x89, 0xb3, 0xa3, 0x41,
	0x2e, 0xce, 0x8e, 0x0e, 0xa4, 0xd2, 0xb9, 0x01, 0x33, 0xe8, 0x7c, 0x1e, 0x72, 0xa2, 0xf3, 0xf9,
	0xb8, 0xa4, 0x55, 0x56, 0xa0, 0x8d, 0x59, 0x59, 0x1d, 0xac, 0xcc, 0xca, 0x1a, 0xd0, 0xe4, 0x2e,
	0x7d, 0xd7, 0xfe, 0xb9, 0xd9, 0xdf, 0x11, 0xbf, 0xec, 0x4f, 0xb9, 0xd6, 0x49, 0x55, 0x7c, 0xef,
	0xfd, 0x17, 0x00, 0x00, 0xff, 0xff, 0x29, 0x5d, 0xa4, 0xe0, 0xd3, 0x0f, 0x00, 0x00,
}
